<?php

include '../modele/pdo.php';

if (!isset($_POST['userLastNameConfirm']))
	return 0;
if (!isset($_POST['userFirstNameConfirm']))
	return 0;
if (!isset($_POST['formationLieu']))
	return 0;
if (!isset($_POST['formationNom']))
	return 0;
if (!isset($_POST['formationDate']))
	return 0;
if (!isset($_POST['formationDate2']))
	return 0;
if (!isset($_POST['radio-stacked']))
	return 0;
if (!isset($_POST['checkNouvelleTechnique']))
	return 0;
if (!isset($_POST['checkPratique']))
	return 0;
if (!isset($_POST['checkAutre']))
	if (!isset($_POST['autreAttentesFin']))
		return 0;
if (!isset($_POST['checkConnaissance']))
	return 0;
if (!isset($_POST['checkAutre']))
	return 0;
if (!isset($_POST['checkAutre']))
	return 0;
if (!isset($_POST['checkAutre']))
	return 0;
if (!isset($_POST['checkAutre']))
	return 0;
if (!isset($_POST['checkAutre']))
	return 0;
if (!isset($_POST['checkAutre']))
	return 0;
if (!isset($_POST['checkAutre']))
	return 0;
if (!isset($_POST['checkAutre']))
	return 0;
if (!isset($_POST['checkAutre']))
	return 0;
if (!isset($_POST['checkAutre']))
	return 0;
if (!isset($_POST['checkAutre']))
	return 0;
?>